### ISSUE TITLE
async keyword generates a different public API

### ISSUE THREAD

**Issue by SeanFeldman** [JakeGinnivan/ApiApprover#19]
If understood correctly, `async` keyword is just a syntax sugar and shouldn't change public API.
Right now it does. Here's a repro:

``` c#
public interface ITopology
{
    Task<bool> RunChecks();
}

public class A : ITopology 
{
    public Task<bool> RunChecks()
    {
        return Task.FromResult(true);
    }
}

public class B : ITopology
{
    public async Task<bool> RunChecks()
    {
        await Task.Delay(1); // mimicing some other call
        await Task.Delay(2); // mimicing some other call
        // logic to generate returned result based on invocations
        return true;
    }
}
```

Generate code is:

``` c#
public class A : ITopology
{
        public System.Threading.Tasks.Task<bool> RunChecks() { }
}   

public class B : ITopology
{
        public async System.Threading.Tasks.Task<bool> RunChecks() { }
}
```

**Comment by danielmarbach** [comment]
@SeanFeldman The async keyword should not be part of the public API at all. I submitted a PR https://github.com/JakeGinnivan/ApiApprover/pull/26

The async keyword is an implementation detail since it is just syntactic sugar. From an API perspective the following APIs are equivalent:

- `async void` vs. `void`
- `async Task` vs `Task`
- `async Task<T>` vs `Task<T>`

From a behavior perspective you could argue that the runtime behavior from `void` to `async void` can change and therefore it could be a breaking change but from an API perspective both APIs are binary compatible. Since API approver's concern is only the public API the `async` keyword should be omitted. Thoughts?
