### ISSUE TITLE
Expose type filtering in PublicApiGenerator.GetPublicApi

### ISSUE THREAD

**Issue by thomaslevesque** [JakeGinnivan/ApiApprover#24]
Currently it's possible to specify which types should be included, but there's no easy way to specify that specific types should be excluded. I see that internally, `GetPublicApi` calls `CreatePublicApiForAssembly`, which accepts a predicate on the types. Exposing this publicly would be very useful.

For completeness, here's my use case: in FakeItEasy, we embed Castle.Core using ILMerge; most of the types are internalized, but some need to be public. I'd like to exclude the Castle types from the approval tests, since they're exposed only "by accident" and are not really part of FakeItEasy's API.

**Comment by danielmarbach** [comment]
@thomaslevesque by exposing those types that are ILMerge as public types they actually become part of your public API. If such a public type changes your API is no longer binary compliant per definition. Can you elaborate?

**Comment by thomaslevesque** [comment]
> by exposing those types that are ILMerge as public types they actually become part of your public API.

True, but they're not *intended* to be part of the public API, they're here only because of a technical constraint.

> If such a public type changes your API is no longer binary compliant per definition. Can you elaborate?

Yes, I realize that binary compatibility will be broken if these types change. But binary compatibility isn't our concern in FakeItEasy; it's a mocking framework, so it's only used in unit tests, not in application code. It's not the kind of thing you just replace without rebuilding; in practice, people will still rebuild their tests projects after upgrading, so it doesn't matter if it's not binary compatible. We use `PublicApiGenerator` only to ensure we don't accidentally introduce breaking changes in the public API.

**Comment by adamralph** [comment]
I'm not sure it's a good idea to exclude anything from the report. The public API is the public API whether it's intended to be or not. E.g. in the case of FakeItEasy, how can we guarantee that noone is linking to the exposed Castle.Core members, even if they shouldn't be?

**Comment by thomaslevesque** [comment]
> E.g. in the case of FakeItEasy, how can we guarantee that noone is linking to the exposed Castle.Core members, even if they shouldn't be?

We can't; but as you say, they shouldn't be doing this. If they need Castle Core, they should use Castle Core, not the small subset of it exposed in FakeIteasy...

**Comment by adamralph** [comment]
Having thought about this more, I think it *might* be a good idea. However, I don't think the FakeItEasy and Castle.Core case is the best example of why.

I'll explain. In some recent projects, I've put internal types in a `Foo.Internal` namespace instead of making them `internal`. Besides the arguably nicer code organisation that this encourages, the reason for doing so is to allow consumers to punch through the public abstractions *if they really want to*, without having to use reflection. After all, `internal` only makes it inconvenient, rather than impossible, to access those types. The types are still subject to change in any version without warning, and often do so, exemplifying the reasons they are intended for internal use only.

Access to internal types is useful when spiking, or for when making a conscious decision to take on an extra maintenance burden when upgrading the package (anything might need to change). I'd rather leave this in the hands of the consumer than making a decision for them, or forcing them to use reflection.

If I ask myself "would I use the exclusion feature if it existed?" the answer is an emphatic "yes I would". The alternative is to either to manually accept all changes that a comparison shows me for types are in the `Foo.Internal` namespace, or to pull those types out of the newly generated string. This is something a computer can do for me, so my first instinct would be to write some code to pull those types out of the API string. I would then ask myself if that facility would be better built into the thing that is generating that string in the first place.

Now, when choosing to publicly expose types intended for internal usage, it's of vital importance to communicate the intent. I believe the `Foo.Internal` namespace does that, and I would encourage anyone choosing to do this to also put an obvious fence around those types by putting them in an appropriate namespace. Given that packages should be steering consumers toward the pit of success, I would implement this feature at a namespace level. I.e.. "exclude all types in namespace `Foo.Internal`".

**Comment by danielmarbach** [comment]
This is the slogan of the project

> Simple project to approve the public API of a project (useful for semantic versioning)

No matter how you'd want to turn it any publicly exposed type in the library is treated as the public API. This is also true of you look at semver and the semver specification. There is no special treatment of conventionally named namespaces which allows you to says as a library author: We are BUTSemver. Everything not in namespace Foo.Internal is Semver BUT the types in that namespace.

I don't think this project should provided such filtering capabilities. I would even go so far that we should remove the existing filtering capabilities

```
public static string CreatePublicApiForAssembly(AssemblyDefinition assembly, Func<TypeDefinition, bool> shouldIncludeType, bool shouldIncludeAssemblyAttributes)
```

and leave it all up to the end-users. It is trivial to write your custom logic for filtering if you really want or need it like we do in NServiceBus

```
        public void ApproveNServiceBus()
        {
            var assemblyPath = Path.GetFullPath(typeof(Endpoint).Assembly.Location);
            var asm = AssemblyDefinition.ReadAssembly(assemblyPath);
            var publicApi = Filter(PublicApiGenerator.CreatePublicApiForAssembly(asm));
            Approvals.Verify(publicApi);
        }

        string Filter(string text)
        {
            return string.Join(Environment.NewLine, text.Split(new[]
            {
                Environment.NewLine
            }, StringSplitOptions.RemoveEmptyEntries)
                .Where(l => !l.StartsWith("[assembly: ReleaseDateAttribute("))
                .Where(l => !string.IsNullOrWhiteSpace(l))
                );
        }
```

I'm leaning towards closing this since I think it should not be a PublicApiGenerator responsibility. @JakeGinnivan thoughts?

**Comment by adamralph** [comment]
I'm not strongly concerned whether this feature makes it in or not. As you say @danielmarbach, I can just write some code to remove those types myself. However, if the feature was added, I'd use it.

Regarding breaking changes and SemVer, this is only tangentially related to this issue, but while SemVer says what you should do when breaking, it doesn't offer any help to define what *breaking* actually is and that is wholly down to interpretation, and ultimately, I don't believe it can ever be anything more formal than an understanding between the producers and consumers of a library. For example, depending on your point of view, [any public change could be said to be a breaking change](https://blogs.msdn.microsoft.com/ericlippert/2012/01/09/every-public-change-is-a-breaking-change/).

**Comment by danielmarbach** [comment]
Closing this as won't fix based on the reasons outlined in this discussion thread
